### PR TITLE
v3.4

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

+

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [ ] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [ ] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>e2e</b> tests created</li>
        <li>- [ ] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

**Comment by jaakkonarhi** [comment]
| Manual test            |                                                    |
| ---------------------- | -------------------------------------------------- |
| Date                   | 2021-11-30                                         |
| Operating system       | macOS Catalina 10.15.7                                        |
| IDEA version           | 2021.2.1                                           |
| Plugin version         | 3.4 (pre-release)                                  |
| Tester                 | @jaakkonarhi                                       |
| Note                   |                                                    |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

- **2.12** Maybe someone should update this
- **3 REMARK.** Add jsoup library
- **4.11** Modules dialog
- **4.19** You should change the theme manually to light first to see if this has any effect
- **5.2. REMARK** The dialog has to be closed for them to be installed and progress isn't shown
-  **6.7** RandomTextApp is highlighted red but still works, but if you import it manually, it's not highlighted and autocomplete works for it.
- **6.45** No dialog show, so can't be sure if it worked
- **8.5** News not loaded until refreshed
- **9.8** Does the whole tree have to be refreshed just to update this
- - **14 REMARK** Use the test user for testing

**Comment by Taikelenn** [comment]
| Manual test            |                                                    |
| ---------------------- | -------------------------------------------------- |
| Date                   | 2021-11-30                                         |
| Operating system       | Ubuntu 20.04                                        |
| IDEA version           | 2021.2.3                                           |
| Plugin version         | 3.4 (pre-release)                                  |
| Tester                 | @Taikelenn                                        |
| Note                   |                                                    |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

- 2.9. This JDK is now called "Eclipse Temurin"
- 2.12. Change the instructions so that it reflects current design
- 3.5. **Remark** - Add jsoup to the library list
- 4.21. Not "inside Assignments view" but in the whole A+ Courses pane
- 5.2. **Remark** - I had to close the Modules window for the module to finish installing
- 5.13. **Remark** - Merely opening the Modules window should be enough for search to work. Right now you need to click on some module, which is redundant.
- 6.2. **Remark** - https://i.imgur.com/zH6Q4t1.png - double quote
- 9.1. **Remark** - If I select GoodStuff assignment while it's not yet lazy-loaded, and loading finishes, the "submit" button doesn't become enabled. I have to select it again.
- 11.3. **FAILED** - I double-clicked on the assignment and got an exception, see below.

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'action' of com/intellij/openapi/actionSystem/AnActionEvent.createFromAnAction must not be null
	at com.intellij.openapi.actionSystem.AnActionEvent.$$$reportNull$$$0(AnActionEvent.java)
	at com.intellij.openapi.actionSystem.AnActionEvent.createFromAnAction(AnActionEvent.java)
	at fi.aalto.cs.apluscourses.intellij.actions.ActionUtil.launch(ActionUtil.java:24)
	at fi.aalto.cs.apluscourses.intellij.actions.ActionUtil.lambda$createOnEventLauncher$0(ActionUtil.java:39)
	at fi.aalto.cs.apluscourses.ui.base.TreeView$TreeMouseListener.lambda$mouseClicked$0(TreeView.java:206)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
	at fi.aalto.cs.apluscourses.ui.base.TreeView$TreeMouseListener.mouseClicked(TreeView.java:206)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:394)
```

**Review by OlliKiljunen — CHANGES_REQUESTED** [review]
| Manual test            |                                                    |
| ---------------------- | -------------------------------------------------- |
| Date                   | 2021-11-30                                         |
| Operating system       | Windows 10                                         |
| IDEA version           | 2021.3                                             |
| Plugin version         | 3.4 (pre-release)                                  |
| Tester                 | @OlliKiljunen                                       |
| Note                   |                                                    |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

- **0.2** These configuration instructions are obsolete.
- **2.2** One should choose "Multi-module project" instead of "Empty project" 
- **2.9** The vendor is now "Eclipse Temurin (AdoptOpenJDK HotSpot)".
- **2.12** Only one label.
- **3.3** The version wasn't updated yet.
- **4.1**, **4.4** (also **4.13**) The name of the menu item has been changed.
- **4.6** Screenshot out-of-date.
- **4.11** Workflow changed!
- **4.12** **FAILED!!!** Scala library ain't installed with O1Library!
- **4.16** **FAILED!!!** No such a prompt??? The rest of the section skipped.
- **5.12** **FAILED!!!** Scala SDK installation doesn't work. I had to add
  Scala SDK as a library manually. Still, the modules show as "Waiting for
  dependencies". Due to these constant failures, testing was interrupted.

**Review by OlliKiljunen — APPROVED** [review]
Now it works on Windows 👍

**Review by Taikelenn — APPROVED** [review]
On Ubuntu works as well

**Pull request merged**
