### PR TITLE
v3.9

### PR DESCRIPTION
**Pull request by Taikelenn**
# Description of the PR
[aplus-courses-3.9.zip](https://github.com/Aalto-LeTech/aplus-courses/files/9653445/aplus-courses-3.9.zip)

### CODE REVIEW

**Comment by OlliKiljunen** [comment]
I'll test it on Ubuntu, ok?

**Comment by Taikelenn** [comment]
I'll test on Windows then

**Review by OlliKiljunen — APPROVED** [review]
| Manual test            |                                                    |
| ---------------------- | -------------------------------------------------- |
| Date                   | 2022-09-29                                         |
| Operating system       | Ubuntu 20.04.5 LTS                                 |
| IDEA version           | 2022.2.2                                           |
| Plugin version         | 3.9 (pre-release)                                  |
| Tester                 | @OlliKiljunen                                      |
| Note                   |                                                    |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

[Link to the testing manual](https://github.com/Aalto-LeTech/aplus-courses/blob/66cbe87a9dfb824fe00464833593d6a155ae6d50/TESTING.md)

### Notes

- 0.1 As it has been discussed in these reports many times before, the setup
      chapter of the testing manual is outdated and should be rewritten.

- 2.9 I chose JDK 17 (Temurin) instead.

- 2.12 UI has changed, as reported earlier. Further notes of this kind are
       omitted.

- 3.5 What about the Zip library?

- 5.19 **REMARK.** Open Documentation action is not available.

- 6.14 I skipped some steps I considered redundant in this chapter.

**Comment by Taikelenn** [comment]
| Manual test            |                                                    |
| ---------------------- | -------------------------------------------------- |
| Date                   | 2022-09-29                                         |
| Operating system       | Windows 10 build 19044                             |
| IDEA version           | 2022.2.2                                           |
| Plugin version         | 3.9 (pre-release)                                  |
| Tester                 | @Taikelenn                                        |
| Note                   |                                                    |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

There are no notes. Instead, TESTING.md has been updated to address long-standing issues.

**Pull request merged**
